version: "3.8"
services:
  mongo:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    depends_on:
      - mongo

volumes:
  data:
