version: "3.8"
services:
  backend:
    container_name: backend
    image: ${DOCKERHUB_USER:-haideralimazari}/wanderlust-backend:${IMAGE_TAG:-latest}
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  frontend:
    container_name: frontend
    image: ${DOCKERHUB_USER:-haideralimazari}/wanderlust-frontend:${IMAGE_TAG:-latest}
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data/db

  redis:
    container_name: redis
    image: redis:7.0.5-alpine

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  data:
